name: shhworld_min
description: ShhWorld stable base with Supabase
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.0
  noise_meter: ^3.0.1
  permission_handler: ^10.4.5
  intl: ^0.19.0
  mapbox_gl: ^0.16.0

flutter:
  uses-material-design: true
